// Drift v2 chain: 366 words, each one meaning-step from the last, wrapping.
// Every entry's pivot describes the step from the PREVIOUS word to this one
// (word[0]'s pivot describes word[365] -> word[0]).
// Run: node scripts/chain_v2.mjs   — validates and writes data/chain.json.

import { writeFileSync } from "node:fs";

// [word, pivot-from-previous]
const CHAIN = [
  // ---- original 72, now with authored pivots (wraps from "bean") ----
  ["coffee", "coffee beans"],
  ["espresso", "espresso is strong coffee"],
  ["latte", "a latte is espresso with milk"],
  ["milk", "the milk in a latte"],
  ["cow", "milk comes from cows"],
  ["pasture", "cows graze in a pasture"],
  ["grass", "a grassy pasture"],
  ["lawn", "a lawn of grass"],
  ["garden", "a lawn and garden"],
  ["flower", "a flower garden"],
  ["bee", "a bee visits flowers"],
  ["honey", "bees make honey"],
  ["tea", "honey in tea"],
  ["kettle", "a tea kettle"],
  ["steam", "a steaming kettle"],
  ["cloud", "steam rises into clouds"],
  ["rain", "rain falls from clouds"],
  ["river", "rain fills the river"],
  ["boat", "a boat on the river"],
  ["sail", "a sailboat"],
  ["wind", "wind fills the sail"],
  ["kite", "wind lifts a kite"],
  ["string", "a kite string"],
  ["guitar", "a guitar string"],
  ["music", "guitar music"],
  ["piano", "piano music"],
  ["key", "piano keys"],
  ["lock", "a key opens a lock"],
  ["door", "a lock on the door"],
  ["house", "the front door of a house"],
  ["roof", "a house's roof"],
  ["chimney", "a chimney on the roof"],
  ["smoke", "smoke from the chimney"],
  ["fire", "smoke means fire"],
  ["candle", "a fire lights a candle"],
  ["wax", "candle wax"],
  ["lamp", "wax in a lava lamp"],
  ["bulb", "a lamp's bulb"],
  ["light", "a bulb gives light"],
  ["sun", "sunlight"],
  ["summer", "the summer sun"],
  ["beach", "a summer beach"],
  ["sand", "beach sand"],
  ["glass", "sand melts into glass"],
  ["bottle", "a glass bottle"],
  ["wine", "a bottle of wine"],
  ["grape", "wine is made from grapes"],
  ["vine", "grapes grow on the vine"],
  ["ivy", "ivy is a climbing vine"],
  ["wood", "ivy climbing old wood"],
  ["tree", "wood comes from trees"],
  ["leaf", "a leaf on the tree"],
  ["paper", "a leaf of paper"],
  ["book", "pages of paper in a book"],
  ["library", "books in a library"],
  ["shelf", "a library shelf"],
  ["pantry", "a pantry shelf"],
  ["flour", "flour in the pantry"],
  ["sugar", "flour and sugar"],
  ["cake", "sugar in the cake"],
  ["oven", "a cake in the oven"],
  ["kitchen", "an oven in the kitchen"],
  ["plate", "a kitchen plate"],
  ["ceramic", "a ceramic plate"],
  ["clay", "ceramic is fired clay"],
  ["earth", "clay dug from the earth"],
  ["soil", "earth is soil"],
  ["seed", "a seed in the soil"],
  ["wheat", "wheat grows from seed"],
  ["bread", "bread is made from wheat"],
  ["toast", "toasted bread"],
  ["breakfast", "toast for breakfast"],
  // ---- v2 continuation ----
  ["egg", "a breakfast egg"],
  ["nest", "eggs in a nest"],
  ["bird", "a bird's nest"],
  ["feather", "birds of a feather"],
  ["pillow", "a feather pillow"],
  ["sleep", "sleeping on a pillow"],
  ["dream", "dreams come with sleep"],
  ["night", "dreams belong to the night"],
  ["owl", "a night owl"],
  ["forest", "owls live in the forest"],
  ["trail", "a forest trail"],
  ["mountain", "a mountain trail"],
  ["peak", "a mountain peak"],
  ["snow", "a snowy peak"],
  ["winter", "winter snow"],
  ["scarf", "a winter scarf"],
  ["wool", "a wool scarf"],
  ["sheep", "wool comes from sheep"],
  ["shepherd", "a shepherd keeps sheep"],
  ["dog", "a sheepdog"],
  ["bone", "a dog's bone"],
  ["skeleton", "bones make a skeleton"],
  ["closet", "a skeleton in the closet"],
  ["coat", "a coat in the closet"],
  ["paint", "a coat of paint"],
  ["brush", "a paintbrush"],
  ["hair", "a hairbrush"],
  ["barber", "a barber cuts hair"],
  ["razor", "a barber's razor"],
  ["blade", "a razor blade"],
  ["knife", "a knife's blade"],
  ["fork", "a knife and fork"],
  ["road", "a fork in the road"],
  ["map", "a road map"],
  ["treasure", "a treasure map"],
  ["chest", "a treasure chest"],
  ["heart", "the heart in your chest"],
  ["beat", "a heartbeat"],
  ["drum", "a drum beat"],
  ["band", "a drummer in the band"],
  ["ring", "a wedding band is a ring"],
  ["bell", "ring the bell"],
  ["church", "church bells"],
  ["choir", "the church choir"],
  ["voice", "voices in a choir"],
  ["echo", "a voice echoes"],
  ["canyon", "echoes in a canyon"],
  ["desert", "a desert canyon"],
  ["camel", "a desert camel"],
  ["oasis", "a camel finds an oasis"],
  ["palm", "palms at the oasis"],
  ["hand", "the palm of your hand"],
  ["glove", "a glove on your hand"],
  ["boxing", "boxing gloves"],
  ["match", "a boxing match"],
  ["flame", "a match's flame"],
  ["moth", "a moth to a flame"],
  ["wing", "a moth's wings"],
  ["airplane", "an airplane's wings"],
  ["pilot", "a pilot flies the plane"],
  ["episode", "a pilot episode"],
  ["series", "episodes of a series"],
  ["season", "a season of the series"],
  ["salt", "season with salt"],
  ["pepper", "salt and pepper"],
  ["spice", "pepper is a spice"],
  ["cinnamon", "cinnamon is a spice"],
  ["roll", "a cinnamon roll"],
  ["dice", "roll the dice"],
  ["casino", "dice at the casino"],
  ["luck", "casino luck"],
  ["clover", "a lucky four-leaf clover"],
  ["field", "a field of clover"],
  ["goal", "a field goal"],
  ["soccer", "a soccer goal"],
  ["stadium", "a soccer stadium"],
  ["crowd", "a stadium crowd"],
  ["wave", "the crowd does the wave"],
  ["ocean", "ocean waves"],
  ["whale", "a whale in the ocean"],
  ["song", "whale song"],
  ["lullaby", "a lullaby is a song"],
  ["baby", "sing a baby a lullaby"],
  ["cradle", "a baby's cradle"],
  ["rock", "rock the cradle"],
  ["stone", "a rock is a stone"],
  ["castle", "a stone castle"],
  ["moat", "a castle's moat"],
  ["dragon", "a dragon guards the moat"],
  ["knight", "a knight fights the dragon"],
  ["armor", "a knight's armor"],
  ["shield", "armor and shield"],
  ["sword", "sword and shield"],
  ["pen", "the pen is mightier than the sword"],
  ["ink", "a pen's ink"],
  ["octopus", "an octopus squirts ink"],
  ["reef", "an octopus on the reef"],
  ["coral", "a coral reef"],
  ["pink", "coral pink"],
  ["rose", "rose pink"],
  ["thorn", "every rose has its thorn"],
  ["cactus", "a cactus has thorns"],
  ["pot", "a potted cactus"],
  ["gold", "a pot of gold"],
  ["medal", "a gold medal"],
  ["champion", "a champion's medal"],
  ["trophy", "a champion's trophy"],
  ["victory", "a trophy for the victory"],
  ["parade", "a victory parade"],
  ["float", "a parade float"],
  ["swim", "float or swim"],
  ["pool", "swim in the pool"],
  ["table", "a pool table"],
  ["chair", "a table and chairs"],
  ["throne", "a throne is a chair"],
  ["crown", "the crown on the throne"],
  ["tooth", "a crown on a tooth"],
  ["fairy", "the tooth fairy"],
  ["tale", "a fairy tale"],
  ["story", "a tale is a story"],
  // ---- block A ----
  ["news", "a news story"],
  ["newspaper", "news in the newspaper"],
  ["headline", "a newspaper headline"],
  ["editor", "an editor writes headlines"],
  ["desk", "an editor's desk"],
  ["drawer", "a desk drawer"],
  ["sock", "socks in a drawer"],
  ["shoe", "socks and shoes"],
  ["lace", "shoelaces"],
  ["dress", "a lace dress"],
  ["wedding", "a wedding dress"],
  ["dance", "dancing at a wedding"],
  ["stage", "dancers on a stage"],
  ["curtain", "the stage curtain"],
  ["window", "curtains on a window"],
  ["view", "the view from a window"],
  ["point", "a viewpoint"],
  ["needle", "needlepoint"],
  ["haystack", "a needle in a haystack"],
  ["barn", "haystacks in a barn"],
  ["horse", "a horse in the barn"],
  ["saddle", "a horse's saddle"],
  ["leather", "a leather saddle"],
  ["jacket", "a leather jacket"],
  ["potato", "a jacket potato"],
  ["couch", "a couch potato"],
  ["cushion", "couch cushions"],
  ["pin", "a pincushion"],
  ["bowling", "bowling pins"],
  ["alley", "a bowling alley"],
  ["cat", "an alley cat"],
  ["nap", "a cat nap"],
  ["blanket", "a nap under a blanket"],
  ["fort", "a blanket fort"],
  ["soldier", "soldiers in a fort"],
  ["toy", "a toy soldier"],
  ["doll", "a doll is a toy"],
  ["puppet", "a puppet is a doll on strings"],
  ["show", "a puppet show"],
  ["ticket", "a ticket to the show"],
  ["lottery", "a lottery ticket"],
  ["number", "lottery numbers"],
  ["phone", "a phone number"],
  ["booth", "a phone booth"],
  ["photo", "a photo booth"],
  ["album", "a photo album"],
  ["record", "a record album"],
  ["player", "a record player"],
  ["coach", "a player's coach"],
  ["office", "the coach's office"],
  // ---- back to the main line ----
  ["building", "an office building"],
  ["brick", "a brick building"],
  ["wall", "a brick wall"],
  ["mural", "a mural on the wall"],
  ["artist", "an artist paints murals"],
  ["studio", "an artist's studio"],
  ["apartment", "a studio apartment"],
  ["rent", "rent an apartment"],
  ["landlord", "pay the landlord rent"],
  ["property", "a landlord's property"],
  ["fence", "a fence around the property"],
  ["neighbor", "a fence between neighbors"],
  ["borrow", "borrow from a neighbor"],
  ["loan", "a borrowed loan"],
  ["bank", "a bank loan"],
  ["vault", "a bank vault"],
  ["gym", "a gymnast's vault"],
  ["sweat", "sweat at the gym"],
  ["towel", "towel off the sweat"],
  ["shower", "a towel after the shower"],
  ["gift", "a bridal shower gift"],
  ["ribbon", "a gift's ribbon"],
  ["bow", "a ribbon tied in a bow"],
  ["arrow", "a bow and arrow"],
  ["target", "an arrow hits the target"],
  ["dart", "darts hit targets"],
  ["frog", "a poison dart frog"],
  ["pond", "a frog in the pond"],
  ["lily", "a pond lily"],
  ["valley", "lily of the valley"],
  ["fog", "fog in the valley"],
  ["horn", "a foghorn"],
  ["trumpet", "a trumpet is a horn"],
  ["jazz", "jazz trumpet"],
  ["club", "a jazz club"],
  ["sandwich", "a club sandwich"],
  ["picnic", "picnic sandwiches"],
  ["basket", "a picnic basket"],
  ["hoop", "a basketball hoop"],
  ["earring", "hoop earrings"],
  ["pearl", "pearl earrings"],
  ["oyster", "a pearl in an oyster"],
  ["shell", "an oyster's shell"],
  ["turtle", "a turtle's shell"],
  ["slow", "slow as a turtle"],
  ["snail", "slow as a snail"],
  ["mail", "snail mail"],
  ["stamp", "a mail stamp"],
  ["passport", "a passport stamp"],
  ["travel", "a passport for travel"],
  ["suitcase", "pack a suitcase to travel"],
  ["wheel", "a suitcase wheel"],
  ["hamster", "a hamster wheel"],
  ["cage", "a hamster cage"],
  ["canary", "a canary in a cage"],
  ["yellow", "canary yellow"],
  ["taxi", "a yellow taxi"],
  ["city", "a city taxi"],
  ["skyline", "the city skyline"],
  ["sunset", "sunset on the skyline"],
  ["orange", "sunset orange"],
  ["juice", "orange juice"],
  ["squeeze", "squeeze the juice"],
  ["lemon", "squeeze a lemon"],
  ["car", "a lemon of a car"],
  ["engine", "a car engine"],
  ["train", "a train engine"],
  ["track", "train tracks"],
  ["race", "a racetrack"],
  ["finish", "a race to the finish"],
  ["line", "the finish line"],
  ["fishing", "a fishing line"],
  ["hook", "a fishing hook"],
  ["bait", "bait on the hook"],
  ["worm", "a worm as bait"],
  ["apple", "a worm in the apple"],
  ["orchard", "an apple orchard"],
  ["harvest", "the orchard harvest"],
  ["moon", "a harvest moon"],
  ["tide", "the moon pulls the tide"],
  ["shore", "the tide meets the shore"],
  ["lighthouse", "a lighthouse on the shore"],
  ["beam", "a lighthouse beam"],
  ["smile", "a beaming smile"],
  ["dimple", "a smile with dimples"],
  ["golf", "a golf ball's dimples"],
  ["green", "the golf green"],
  ["salad", "a green salad"],
  ["dressing", "salad dressing"],
  ["wound", "dressing a wound"],
  ["bandage", "a bandage on the wound"],
  ["mummy", "a mummy wrapped in bandages"],
  ["pyramid", "a mummy in a pyramid"],
  ["triangle", "a pyramid is a triangle"],
  ["angle", "a triangle's angles"],
  ["corner", "an angle makes a corner"],
  ["street", "a street corner"],
  ["market", "a street market"],
  ["stock", "the stock market"],
  ["soup", "soup stock"],
  ["spoon", "soup with a spoon"],
  ["silver", "a silver spoon"],
  ["screen", "the silver screen"],
  ["movie", "a movie on the screen"],
  ["popcorn", "movie popcorn"],
  ["kernel", "a popcorn kernel"],
  ["corn", "kernels of corn"],
  ["maze", "a corn maze"],
  ["puzzle", "a maze is a puzzle"],
  ["piece", "a puzzle piece"],
  ["pie", "a piece of pie"],
  ["crust", "a pie crust"],
  ["pizza", "a pizza crust"],
  ["slice", "a pizza slice"],
  ["tennis", "a slice serve in tennis"],
  ["court", "a tennis court"],
  ["judge", "a judge holds court"],
  ["jury", "judge and jury"],
  ["verdict", "the jury's verdict"],
  ["guilty", "a guilty verdict"],
  ["pleasure", "a guilty pleasure"],
  ["chocolate", "chocolate is a pleasure"],
  ["cocoa", "chocolate comes from cocoa"],
  ["bean", "a cocoa bean"],
];

// ---- validation ----
const errors = [];
if (CHAIN.length !== 366) errors.push(`chain length ${CHAIN.length}, want 366`);
const seen = new Map();
CHAIN.forEach(([w, pivot], i) => {
  if (!/^[a-z]+$/.test(w)) errors.push(`bad word at ${i}: "${w}"`);
  if (!pivot || pivot.length < 4) errors.push(`missing pivot at ${i} (${w})`);
  if (seen.has(w)) errors.push(`duplicate "${w}" at ${i} (first at ${seen.get(w)})`);
  seen.set(w, i);
});
if (errors.length) {
  console.error(errors.join("\n"));
  process.exit(1);
}

const out = {
  epoch: "2026-01-01",
  timezone: "America/Los_Angeles",
  words: CHAIN.map(([w, pivot]) => ({ w, pivot })),
};
writeFileSync(new URL("../data/chain.json", import.meta.url), JSON.stringify(out, null, 1) + "\n");
console.log(`wrote data/chain.json: ${CHAIN.length} words, all unique, all pivots present`);
